/**
 * Row convention, used everywhere in this tool:
 *
 *   R1 = bottom row (modifiers / spacebar, nearest the user)
 *   R3 = home row
 *   R5 = number / function row (farthest from the user)
 *
 * `tilt` is degrees of rotation about the X axis applied to the top plate,
 * positive raising the back (+Y) edge so the surface faces the user. `rise` is
 * how much taller the row sits than the home row, in units of the profile's
 * own `sculptScale`, giving every sculpted profile the same bowl shape at its
 * own magnitude. `shift` nudges the top plate front-to-back in millimetres.
 */
export const SCULPT_ROWS = {
  1: { rise: 1.0, tilt: -6, shift: 0.25 },
  2: { rise: 0.2, tilt: -2, shift: 0.1 },
  3: { rise: 0.0, tilt: 2, shift: 0.0 },
  4: { rise: 0.7, tilt: 6, shift: -0.15 },
  5: { rise: 1.6, tilt: 10, shift: -0.3 },
};

const APPROXIMATION_NOTE =
  "Approximated from public community references, not manufacturer CAD.";

function trademarkNote(owner) {
  return `${APPROXIMATION_NOTE} The profile name is associated with ${owner}; this is an independent look-alike.`;
}

/**
 * Every profile. `homeHeight` is the height of the top plate above the cap's
 * open bottom before the dish is cut; sculpted profiles derive their other
 * rows from it via SCULPT_ROWS and `sculptScale`.
 */
export const PROFILES = [
  {
    id: "dsa",
    name: "DSA",
    mount: "mx",
    sculpted: false,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 7.6,
    topWidth: 13.0,
    topDepth: 13.0,
    cornerRadius: 1.0,
    topCornerRadius: 3.0,
    wallBow: 1.0,
    dish: { type: "spherical", depth: 1.5 },
    notes: trademarkNote("Signature Plastics"),
  },
  {
    id: "xda",
    name: "XDA",
    mount: "mx",
    sculpted: false,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 9.1,
    topWidth: 14.2,
    topDepth: 14.2,
    cornerRadius: 1.0,
    topCornerRadius: 2.5,
    wallBow: 1.0,
    dish: { type: "spherical", depth: 1.2 },
    notes: trademarkNote("XDA / MelGeek"),
  },
  {
    id: "kam",
    name: "KAM",
    mount: "mx",
    sculpted: false,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 10.5,
    topWidth: 13.6,
    topDepth: 13.6,
    cornerRadius: 1.0,
    topCornerRadius: 3.0,
    wallBow: 1.05,
    dish: { type: "spherical", depth: 1.3 },
    notes: trademarkNote("Keyreative"),
  },
  {
    id: "g20",
    name: "G20",
    mount: "mx",
    sculpted: false,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 8.9,
    topWidth: 15.0,
    topDepth: 15.0,
    cornerRadius: 1.0,
    topCornerRadius: 2.0,
    wallBow: 1.0,
    dish: { type: "flat", depth: 0 },
    notes: trademarkNote("Signature Plastics"),
  },
  {
    id: "choc",
    name: "Choc (low profile)",
    mount: "choc",
    sculpted: false,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 5.0,
    topWidth: 14.0,
    topDepth: 13.2,
    cornerRadius: 0.8,
    topCornerRadius: 1.6,
    wallBow: 1.0,
    dish: { type: "cylindrical", depth: 0.8 },
    notes: `${APPROXIMATION_NOTE} Low-profile cap for Kailh Choc switches.`,
  },
  {
    id: "cherry",
    name: "Cherry",
    mount: "mx",
    sculpted: true,
    sculptScale: 1.0,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 9.4,
    topWidth: 12.4,
    topDepth: 12.0,
    cornerRadius: 1.0,
    topCornerRadius: 1.5,
    wallBow: 1.0,
    dish: { type: "cylindrical", depth: 1.1 },
    notes: trademarkNote("Cherry / GMK"),
  },
  {
    id: "dcs",
    name: "DCS",
    mount: "mx",
    sculpted: true,
    sculptScale: 1.0,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 10.4,
    topWidth: 12.4,
    topDepth: 12.0,
    cornerRadius: 1.0,
    topCornerRadius: 1.5,
    wallBow: 1.0,
    dish: { type: "cylindrical", depth: 1.2 },
    notes: trademarkNote("Signature Plastics"),
  },
  {
    id: "oem",
    name: "OEM",
    mount: "mx",
    sculpted: true,
    sculptScale: 1.0,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 11.9,
    topWidth: 12.6,
    topDepth: 12.0,
    cornerRadius: 1.0,
    topCornerRadius: 1.5,
    wallBow: 1.0,
    dish: { type: "cylindrical", depth: 1.2 },
    notes: APPROXIMATION_NOTE,
  },
  {
    id: "mda",
    name: "MDA",
    mount: "mx",
    sculpted: true,
    sculptScale: 0.8,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 10.5,
    topWidth: 13.6,
    topDepth: 13.6,
    cornerRadius: 1.0,
    topCornerRadius: 3.0,
    wallBow: 1.05,
    dish: { type: "spherical", depth: 1.6 },
    notes: trademarkNote("Maxkey"),
  },
  {
    id: "kat",
    name: "KAT",
    mount: "mx",
    sculpted: true,
    sculptScale: 0.9,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 13.5,
    topWidth: 13.2,
    topDepth: 13.2,
    cornerRadius: 1.0,
    topCornerRadius: 2.6,
    wallBow: 1.1,
    dish: { type: "spherical", depth: 1.5 },
    notes: trademarkNote("Keyreative"),
  },
  {
    id: "mt3",
    name: "MT3",
    mount: "mx",
    sculpted: true,
    sculptScale: 1.0,
    rows: [1, 2, 3, 4, 5],
    homeHeight: 13.0,
    topWidth: 13.0,
    topDepth: 12.6,
    cornerRadius: 1.0,
    topCornerRadius: 2.2,
    wallBow: 1.15,
    dish: { type: "spherical", depth: 2.4 },
    notes: trademarkNote("Drop / matt3o"),
  },
  {
    id: "sa",
    name: "SA",
    mount: "mx",
    sculpted: true,
    sculptScale: 1.6,
    rows: [1, 2, 3, 4],
    homeHeight: 16.5,
    topWidth: 12.6,
    topDepth: 12.6,
    cornerRadius: 1.0,
    topCornerRadius: 2.0,
    wallBow: 1.0,
    dish: { type: "spherical", depth: 1.6 },
    notes: trademarkNote("Signature Plastics"),
  },
];
